name: Python CI/CD to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  deploy_to_render:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      RENDER_API_KEY: ${{ secrets.rnd_S8qB6SWCarKRy7qvDIeiTnXlphyo }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-d01mklfgi27c73er7ea0?key=vTjUVzInmrc \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"serviceId": "srv-d01mklfgi27c73er7ea0"}'
